name: keepalive

on:
  schedule:
    - cron: "0 3 1 * *"  # todo dia 1 às 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Atualiza timestamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .keepalive
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .keepalive
          git commit -m "keepalive: $(date -u +"%F %T")" || echo "Nada a commitar"
          git push
